import type { Metadata } from "next"
import "./globals.css"
import Header from "@/components/Header"
import CartProviderWrapper from "@/components/CartProviderWrapper"
import AuthProviderWrapper from "@/components/AuthProviderWrapper"

export const metadata: Metadata = {
  title: "Bill's Citrus Cleaner",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <AuthProviderWrapper>
          <CartProviderWrapper>
            <Header />
            {children}
          </CartProviderWrapper>
        </AuthProviderWrapper>
      </body>
    </html>
  )
}
